//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WixWPFWizardBA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WixWPFWizardBA.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional SQL Server installation parameters.
        /// </summary>
        public static string AdvancedConfigurationPage_AdditionalSqlServerInstallParameters {
            get {
                return ResourceManager.GetString("AdvancedConfigurationPage_AdditionalSqlServerInstallParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use recommended settings.
        /// </summary>
        public static string AdvancedConfigurationPage_HideAdvancedSettingsCheckbox {
            get {
                return ResourceManager.GetString("AdvancedConfigurationPage_HideAdvancedSettingsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation path for {0}.
        /// </summary>
        public static string AdvancedConfigurationPage_InstallationPathLabel {
            get {
                return ResourceManager.GetString("AdvancedConfigurationPage_InstallationPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string BootrapperUpdateCheckPage_CheckingForUpdatesMessage {
            get {
                return ResourceManager.GetString("BootrapperUpdateCheckPage_CheckingForUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Error while installing.
        /// </summary>
        public static string BootstrapperManager_InstallErrorMessageTitle {
            get {
                return ResourceManager.GetString("BootstrapperManager_InstallErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of is {0} already installed.
        /// </summary>
        public static string BootstrapperManager_NewerVersionInstalledMessage {
            get {
                return ResourceManager.GetString("BootstrapperManager_NewerVersionInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Newer version already installed.
        /// </summary>
        public static string BootstrapperManager_NewerVersionInstalledTitle {
            get {
                return ResourceManager.GetString("BootstrapperManager_NewerVersionInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new installer.
        /// </summary>
        public static string BootstrapperUpdateAvailablePage_DownloadNewInstallerButtonText {
            get {
                return ResourceManager.GetString("BootstrapperUpdateAvailablePage_DownloadNewInstallerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the installer for {0} is available..
        /// </summary>
        public static string BootstrapperUpdateAvailablePage_NewInstallerAvailableMessage {
            get {
                return ResourceManager.GetString("BootstrapperUpdateAvailablePage_NewInstallerAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run new installer.
        /// </summary>
        public static string BootstrapperUpdateAvailablePage_RunNewInstallerButtonText {
            get {
                return ResourceManager.GetString("BootstrapperUpdateAvailablePage_RunNewInstallerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseButtonText {
            get {
                return ResourceManager.GetString("BrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation is already in progress..
        /// </summary>
        public static string CancelAlreadyInProgressMessageBoxBody {
            get {
                return ResourceManager.GetString("CancelAlreadyInProgressMessageBoxBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Install.
        /// </summary>
        public static string CancelAlreadyInProgressMessageBoxTitle {
            get {
                return ResourceManager.GetString("CancelAlreadyInProgressMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the installation of {0}?.
        /// </summary>
        public static string CancelDialogBody {
            get {
                return ResourceManager.GetString("CancelDialogBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Installer.
        /// </summary>
        public static string CancelDialogTitle {
            get {
                return ResourceManager.GetString("CancelDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t cancel the installation at this stage..
        /// </summary>
        public static string CancelUnavailableMessageBoxBody {
            get {
                return ResourceManager.GetString("CancelUnavailableMessageBoxBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Install.
        /// </summary>
        public static string CancelUnavailableMessageBoxTitle {
            get {
                return ResourceManager.GetString("CancelUnavailableMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional settings.
        /// </summary>
        public static string ConfigurationPage_AdditionalServerSettingsHeader {
            get {
                return ResourceManager.GetString("ConfigurationPage_AdditionalServerSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client only.
        /// </summary>
        public static string ConfigurationPage_InstallationTypeClient {
            get {
                return ResourceManager.GetString("ConfigurationPage_InstallationTypeClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the client will be installed. A server will have to be installed on a different computer on the network..
        /// </summary>
        public static string ConfigurationPage_InstallationTypeClientDescription {
            get {
                return ResourceManager.GetString("ConfigurationPage_InstallationTypeClientDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client and server.
        /// </summary>
        public static string ConfigurationPage_InstallationTypeServer {
            get {
                return ResourceManager.GetString("ConfigurationPage_InstallationTypeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both the client and the server will be installed..
        /// </summary>
        public static string ConfigurationPage_InstallationTypeServerDescription {
            get {
                return ResourceManager.GetString("ConfigurationPage_InstallationTypeServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server 2014 R2 Express with Advanced Services is already installed..
        /// </summary>
        public static string ConfigurationPage_SqlServerAlreadyUpToDateMessage {
            get {
                return ResourceManager.GetString("ConfigurationPage_SqlServerAlreadyUpToDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance name:.
        /// </summary>
        public static string ConfigurationPage_SqlServerInstanceNameTextBoxLabel {
            get {
                return ResourceManager.GetString("ConfigurationPage_SqlServerInstanceNameTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server 2014 R2 Express with Advanced Services will be patched..
        /// </summary>
        public static string ConfigurationPage_SqlServerPatchWillBePerformedMessage {
            get {
                return ResourceManager.GetString("ConfigurationPage_SqlServerPatchWillBePerformedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown SQL Server installation state..
        /// </summary>
        public static string ConfigurationPage_SqlServerUnknownInstallationStateMessage {
            get {
                return ResourceManager.GetString("ConfigurationPage_SqlServerUnknownInstallationStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unsupported upgrade path has been detected. This might be caused by 32-bit SQL Server being installed on a 64-bit operating system. You will have to upgrade SQL Server to SQL Server 2014 R2 Express with Advanced Services manually..
        /// </summary>
        public static string ConfigurationPage_SqlServerUnsupportedUpgradeTypeMessage {
            get {
                return ResourceManager.GetString("ConfigurationPage_SqlServerUnsupportedUpgradeTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server 2014 R2 Express with Advanced Services will be installed on this computer..
        /// </summary>
        public static string ConfigurationPage_SqlServerWillBeInstalledMessage {
            get {
                return ResourceManager.GetString("ConfigurationPage_SqlServerWillBeInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existing installation of SQL Server will be upgraded to SQL Server 2014 R2 Express with Advanced Services..
        /// </summary>
        public static string ConfigurationPage_SqlServerWillBeUpgradedMessage {
            get {
                return ResourceManager.GetString("ConfigurationPage_SqlServerWillBeUpgradedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation was cancelled..
        /// </summary>
        public static string FinishErrorPage_FinishErrorCanceled {
            get {
                return ResourceManager.GetString("FinishErrorPage_FinishErrorCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection error..
        /// </summary>
        public static string FinishErrorPage_FinishErrorConnectionError {
            get {
                return ResourceManager.GetString("FinishErrorPage_FinishErrorConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t download additional packages from the internet..
        /// </summary>
        public static string FinishErrorPage_FinishErrorCouldntDownloadInstallPackages {
            get {
                return ResourceManager.GetString("FinishErrorPage_FinishErrorCouldntDownloadInstallPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t retrieve additional packages..
        /// </summary>
        public static string FinishErrorPage_FinishErrorCouldntRetrieveInstallPackages {
            get {
                return ResourceManager.GetString("FinishErrorPage_FinishErrorCouldntRetrieveInstallPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred, status code: 0x{0:X8}.
        /// </summary>
        public static string FinishErrorPage_FinishErrorUnknown {
            get {
                return ResourceManager.GetString("FinishErrorPage_FinishErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string FinishPage_ExitButtonText {
            get {
                return ResourceManager.GetString("FinishPage_ExitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully installed..
        /// </summary>
        public static string FinishPage_InstallationFinishedSuccessfully {
            get {
                return ResourceManager.GetString("FinishPage_InstallationFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An offline installer for {0} has been created successfully..
        /// </summary>
        public static string FinishPage_LayoutFinishedSuccessfully {
            get {
                return ResourceManager.GetString("FinishPage_LayoutFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully modified..
        /// </summary>
        public static string FinishPage_ModificationFinishedSuccessfully {
            get {
                return ResourceManager.GetString("FinishPage_ModificationFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot now.
        /// </summary>
        public static string FinishPage_RebootButtonText {
            get {
                return ResourceManager.GetString("FinishPage_RebootButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully repaired..
        /// </summary>
        public static string FinishPage_RepairFinishedSuccessfully {
            get {
                return ResourceManager.GetString("FinishPage_RepairFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete the installation, the computer must be rebooted..
        /// </summary>
        public static string FinishPage_RestartRequired {
            get {
                return ResourceManager.GetString("FinishPage_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully removed..
        /// </summary>
        public static string FinishPage_UninstallFinishedSuccessfully {
            get {
                return ResourceManager.GetString("FinishPage_UninstallFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string InstallButtonText {
            get {
                return ResourceManager.GetString("InstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a directory to save the complete installer for {0} to:.
        /// </summary>
        public static string LayoutConfigurationPage_LayoutPathLabel {
            get {
                return ResourceManager.GetString("LayoutConfigurationPage_LayoutPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the license agreement.
        /// </summary>
        public static string LicensePage_AcceptLicenseAgreementCheckboxText {
            get {
                return ResourceManager.GetString("LicensePage_AcceptLicenseAgreementCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.6.2.
        /// </summary>
        public static string Package_Netfx462Redist {
            get {
                return ResourceManager.GetString("Package_Netfx462Redist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server 2014 R2 Express with Advanced Services.
        /// </summary>
        public static string Package_Sql2014Express {
            get {
                return ResourceManager.GetString("Package_Sql2014Express", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server 2014 R2 Express with Advanced Services patch.
        /// </summary>
        public static string Package_Sql2014ExpressPatch {
            get {
                return ResourceManager.GetString("Package_Sql2014ExpressPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update to SQL Server 2014 R2 Express with Advanced Services.
        /// </summary>
        public static string Package_Sql2014ExpressUpgrade {
            get {
                return ResourceManager.GetString("Package_Sql2014ExpressUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WixWpfWizardBA Demo msi.
        /// </summary>
        public static string Package_WixWpfWizardBaDemoMsi {
            get {
                return ResourceManager.GetString("Package_WixWpfWizardBaDemoMsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.6.2.
        /// </summary>
        public static string PackageConfiguration_PackageList__NET_Framework_4_6_2 {
            get {
                return ResourceManager.GetString("PackageConfiguration_PackageList__NET_Framework_4_6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server 2014 with Advanced Services (32-bit).
        /// </summary>
        public static string PackageConfiguration_PackageList_SQL_Server_2014_with_Advanced_Services__32_bit_ {
            get {
                return ResourceManager.GetString("PackageConfiguration_PackageList_SQL_Server_2014_with_Advanced_Services__32_bit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server 2014 with Advanced Services (32-bit) patch.
        /// </summary>
        public static string PackageConfiguration_PackageList_SQL_Server_2014_with_Advanced_Services__32_bit__patch {
            get {
                return ResourceManager.GetString("PackageConfiguration_PackageList_SQL_Server_2014_with_Advanced_Services__32_bit__" +
                        "patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server 2014 with Advanced Services (64-bit).
        /// </summary>
        public static string PackageConfiguration_PackageList_SQL_Server_2014_with_Advanced_Services__64_bit_ {
            get {
                return ResourceManager.GetString("PackageConfiguration_PackageList_SQL_Server_2014_with_Advanced_Services__64_bit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server 2014 with Advanced Services (64-bit) patch.
        /// </summary>
        public static string PackageConfiguration_PackageList_SQL_Server_2014_with_Advanced_Services__64_bit__patch {
            get {
                return ResourceManager.GetString("PackageConfiguration_PackageList_SQL_Server_2014_with_Advanced_Services__64_bit__" +
                        "patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to SQL Server 2014 with Advanced Services (32-bit).
        /// </summary>
        public static string PackageConfiguration_PackageList_Upgrade_to_SQL_Server_2014_with_Advanced_Services__32_bit_ {
            get {
                return ResourceManager.GetString("PackageConfiguration_PackageList_Upgrade_to_SQL_Server_2014_with_Advanced_Service" +
                        "s__32_bit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to SQL Server 2014 with Advanced Services (64-bit).
        /// </summary>
        public static string PackageConfiguration_PackageList_Upgrade_to_SQL_Server_2014_with_Advanced_Services__64_bit_ {
            get {
                return ResourceManager.GetString("PackageConfiguration_PackageList_Upgrade_to_SQL_Server_2014_with_Advanced_Service" +
                        "s__64_bit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WixWpfWizardBA Demo msi.
        /// </summary>
        public static string PackageConfiguration_PackageList_WixWpfWizardBA_Demo_msi {
            get {
                return ResourceManager.GetString("PackageConfiguration_PackageList_WixWpfWizardBA_Demo_msi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning installation of {0}....
        /// </summary>
        public static string PlanPage_PlanningMessage {
            get {
                return ResourceManager.GetString("PlanPage_PlanningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching WixWPFWizardBA installation files on the local computer....
        /// </summary>
        public static string ProgressPage_CachingTextMain {
            get {
                return ResourceManager.GetString("ProgressPage_CachingTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing additional components..
        /// </summary>
        public static string ProgressPage_InstallingComponentsTextMain {
            get {
                return ResourceManager.GetString("ProgressPage_InstallingComponentsTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don&apos;t turn off the computer. Doing so may result in damage to the operating system..
        /// </summary>
        public static string ProgressPage_InstallingTextDontTurnOffComputer {
            get {
                return ResourceManager.GetString("ProgressPage_InstallingTextDontTurnOffComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process may take from several seconds to several hours to complete..
        /// </summary>
        public static string ProgressPage_InstallingTextLine1 {
            get {
                return ResourceManager.GetString("ProgressPage_InstallingTextLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing components will be downloaded from the internet automatically..
        /// </summary>
        public static string ProgressPage_InstallingTextLine2 {
            get {
                return ResourceManager.GetString("ProgressPage_InstallingTextLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing WixWPFWizardBA..
        /// </summary>
        public static string ProgressPage_InstallingTextMain {
            get {
                return ResourceManager.GetString("ProgressPage_InstallingTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an offline installer for WixWPFWizardBA..
        /// </summary>
        public static string ProgressPage_LayoutInProgressTextMain {
            get {
                return ResourceManager.GetString("ProgressPage_LayoutInProgressTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can take some time, depending on the parameters of your internet connection..
        /// </summary>
        public static string ProgressPage_LayoutInProgressTextMayTakeSomeTime {
            get {
                return ResourceManager.GetString("ProgressPage_LayoutInProgressTextMayTakeSomeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching &quot;{0}&quot;.
        /// </summary>
        public static string ProgressPage_ProgressCachingEntryText {
            get {
                return ResourceManager.GetString("ProgressPage_ProgressCachingEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying &quot;{0}&quot;.
        /// </summary>
        public static string ProgressPage_ProgressCopyEntryText {
            get {
                return ResourceManager.GetString("ProgressPage_ProgressCopyEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading &quot;{0}&quot;.
        /// </summary>
        public static string ProgressPage_ProgressDownloadEntryText {
            get {
                return ResourceManager.GetString("ProgressPage_ProgressDownloadEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &quot;{0}&quot;.
        /// </summary>
        public static string ProgressPage_ProgressExecuteEntryText {
            get {
                return ResourceManager.GetString("ProgressPage_ProgressExecuteEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting &quot;{0}&quot;.
        /// </summary>
        public static string ProgressPage_ProgressExtractEntryText {
            get {
                return ResourceManager.GetString("ProgressPage_ProgressExtractEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing WixWPFWizardBA..
        /// </summary>
        public static string ProgressPage_RemovingTextMain {
            get {
                return ResourceManager.GetString("ProgressPage_RemovingTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing WixWPFWizardBA..
        /// </summary>
        public static string ProgressPage_RepairingTextMain {
            get {
                return ResourceManager.GetString("ProgressPage_RepairingTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total progress: {0}%.
        /// </summary>
        public static string ProgressPage_TotalProgressText {
            get {
                return ResourceManager.GetString("ProgressPage_TotalProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We recommend that you visit the website and check out what&apos;s new..
        /// </summary>
        public static string ProgressPage_UpdatingTextLine2 {
            get {
                return ResourceManager.GetString("ProgressPage_UpdatingTextLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating WixWPFWizardBA..
        /// </summary>
        public static string ProgressPage_UpdatingTextMain {
            get {
                return ResourceManager.GetString("ProgressPage_UpdatingTextMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add components.
        /// </summary>
        public static string WelcomePage_AddComponentsButtonText {
            get {
                return ResourceManager.GetString("WelcomePage_AddComponentsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string WelcomePage_InstallButtonText {
            get {
                return ResourceManager.GetString("WelcomePage_InstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an offline installer.
        /// </summary>
        public static string WelcomePage_LayoutButtonText {
            get {
                return ResourceManager.GetString("WelcomePage_LayoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        public static string WelcomePage_RepairButtonText {
            get {
                return ResourceManager.GetString("WelcomePage_RepairButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string WelcomePage_UninstallButtonText {
            get {
                return ResourceManager.GetString("WelcomePage_UninstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string WelcomePage_UpdateButtonText {
            get {
                return ResourceManager.GetString("WelcomePage_UpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the graphical installer for {0}!.
        /// </summary>
        public static string WelcomePage_WelcomeText {
            get {
                return ResourceManager.GetString("WelcomePage_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Wizard_BackButtonText {
            get {
                return ResourceManager.GetString("Wizard_BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Wizard_CancelButtonText {
            get {
                return ResourceManager.GetString("Wizard_CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Creating offline installer.
        /// </summary>
        public static string Wizard_HeaderCreatingOfflineInstaller {
            get {
                return ResourceManager.GetString("Wizard_HeaderCreatingOfflineInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0}.
        /// </summary>
        public static string Wizard_HeaderInstalling {
            get {
                return ResourceManager.GetString("Wizard_HeaderInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying {0}.
        /// </summary>
        public static string Wizard_HeaderModifying {
            get {
                return ResourceManager.GetString("Wizard_HeaderModifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing {0}.
        /// </summary>
        public static string Wizard_HeaderRemoving {
            get {
                return ResourceManager.GetString("Wizard_HeaderRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing {0}.
        /// </summary>
        public static string Wizard_HeaderRepairing {
            get {
                return ResourceManager.GetString("Wizard_HeaderRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Wizard_NextButtonText {
            get {
                return ResourceManager.GetString("Wizard_NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Setup {1}.
        /// </summary>
        public static string Wizard_WindowTitle {
            get {
                return ResourceManager.GetString("Wizard_WindowTitle", resourceCulture);
            }
        }
    }
}
